### ISSUE TITLE
reddit data has invalid label - out of index

### ISSUE THREAD

**Issue by ogencoglu** [jing-qian/A-Benchmark-Dataset-for-Learning-to-Intervene-in-Online-Hate-Speech#3]
Sample 3379 from **reddit** data has two posts but the hate speech annotation is `[3]`. Verified both in python `pandas` and in Ubuntu LibreOffice Calc.

Here:
![image](https://user-images.githubusercontent.com/8182738/82956378-58743b80-9fb9-11ea-894c-7cabe762bb96.png)

Any ideas?

**Comment by mbaghou** [comment]
It's just a typo error. Change manually [3] by [2]
