### ISSUE TITLE
Hate speech indexes

### ISSUE THREAD

**Issue by pranavnbapat** [jing-qian/A-Benchmark-Dataset-for-Learning-to-Intervene-in-Online-Hate-Speech#4]
What are the hate speech indexes? They are just numbers, what is to be derived from them? Even the paper doesn't mention about them.

**Comment by jing-qian** [comment]
I am not sure if I understand your question correctly. Each post in a conversation snippet is indexed, starting from 1. Hate_speech_idx includes those indexes whose corresponding post is hate speech. You may use the hate_speech_idx field to identify the hateful posts in this conversation.
